# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: example
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
host_network: false
host_dbus: true
map:
  - share:rw
ports:
  8080/tcp: 8080
options:
  lock_MAC: null
schema:
  lock_MAC: str
