version: '3.8'
services:
  nuki-bridge:
    container_name: 'nuki-bridge'
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_FROM: 'ghcr.io/hassio-addons/base-python:9.0.1'
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z

