# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Nuki Bridge"
description: "Nuki Local Bridge inspired by RaspiNukiBridge"
version: "0.0.1"
slug: "Nuki Bridge"
url: "https://github.com/victorigualada/homeassistant-addons/tree/main/nuki-bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ports:
  8080/tcp: 8087
host_network: false
host_dbus: true
options:
  lock_MAC: null
schema:
  lock_MAC: str?
